spring:
  profiles:
    active: pro
  freemarker:
    suffix: .flt
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: utf-8
    # 设置页面缓存
    cache: false
    #设置模板更新的延时时间
    settings:
      template_update_delay: 0
    # 设置ftl文件路径
    template-loader-path: classpath:/views/
    request-context-attribute: req
  mvc:
    static-path-pattern: /static/**
  rabbitmq:
    host: 123.207.0.121
    port: 5672
    username: doilike
    password: webdoilike
  redis:
   #Redis数据库索引(默认为0)
    database: 0
   #Redis 服务器地址
    host: 123.207.0.121
   #Redis 端口
    port: 12000
   #Redis 连接密码(默认是 空的)
    password: potatos123
    pool:
      #Redis 连接池最大数
      max-active: 200
      #Redis 连接池最大堵塞等待时间 为 负数表示没有限制
      max-wait: -1
      #Redis 最大空闲连接数
      max-idle: 10
      #Redis 最小空闲连接数
      min-idle: 0
    #Redis 超时时间(毫秒)
    timeout: 3000
      